config/routes.rb
Rails.application.routes.draw do
  root "home_page#index"
  resources :app_bookmarks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/app_bookmark.rb
class AppBookmark < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/controllers/app_bookmarks_controller.rb
class AppBookmarksController < ApplicationController
  before_action :set_app_bookmark, only: %i[ show edit update destroy ]

  # GET /app_bookmarks or /app_bookmarks.json
  def index
    @app_bookmarks = AppBookmark.all
  end

  # GET /app_bookmarks/1 or /app_bookmarks/1.json
  def show
  end

  # GET /app_bookmarks/new
  def new
    @app_bookmark = AppBookmark.new
  end

  # GET /app_bookmarks/1/edit
  def edit
  end

  # POST /app_bookmarks or /app_bookmarks.json
  def create
    @app_bookmark = AppBookmark.new(app_bookmark_params)

    respond_to do |format|
      if @app_bookmark.save
        format.html { redirect_to @app_bookmark, notice: "App bookmark was successfully created." }
        format.json { render :show, status: :created, location: @app_bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @app_bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_bookmarks/1 or /app_bookmarks/1.json
  def update
    respond_to do |format|
      if @app_bookmark.update(app_bookmark_params)
        format.html { redirect_to @app_bookmark, notice: "App bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @app_bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @app_bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_bookmarks/1 or /app_bookmarks/1.json
  def destroy
    @app_bookmark.destroy!

    respond_to do |format|
      format.html { redirect_to app_bookmarks_path, status: :see_other, notice: "App bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_bookmark
      @app_bookmark = AppBookmark.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def app_bookmark_params
      params.fetch(:app_bookmark, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/helpers/app_bookmarks_helper.rb
module AppBookmarksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/app_bookmarks/_app_bookmark.html.erb
<div id="<%= dom_id app_bookmark %>" class="w-full sm:w-auto my-5 space-y-5">
</div>

app/views/app_bookmarks/_form.html.erb
<%= form_with(model: app_bookmark, class: "contents") do |form| %>
  <% if app_bookmark.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(app_bookmark.errors.count, "error") %> prohibited this app_bookmark from being saved:</h2>

      <ul class="list-disc ml-6">
        <% app_bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/app_bookmarks/edit.html.erb
<% content_for :title, "Editing app bookmark" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing app bookmark</h1>

  <%= render "form", app_bookmark: @app_bookmark %>

  <%= link_to "Show this app bookmark", @app_bookmark, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to app bookmarks", app_bookmarks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/app_bookmarks/index.html.erb
<% content_for :title, "App bookmarks" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">App bookmarks</h1>
    <%= link_to "New app bookmark", new_app_bookmark_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="app_bookmarks" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @app_bookmarks.any? %>
      <% @app_bookmarks.each do |app_bookmark| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render app_bookmark %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", app_bookmark, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_app_bookmark_path(app_bookmark), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="sm:inline-block">
              <%= button_to "Destroy", app_bookmark, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No app bookmarks found.</p>
    <% end %>
  </div>
</div>

app/views/app_bookmarks/new.html.erb
<% content_for :title, "New app bookmark" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New app bookmark</h1>

  <%= render "form", app_bookmark: @app_bookmark %>

  <%= link_to "Back to app bookmarks", app_bookmarks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/app_bookmarks/show.html.erb
<% content_for :title, "Showing app bookmark" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing app bookmark</h1>

  <%= render @app_bookmark %>

  <%= link_to "Edit this app bookmark", edit_app_bookmark_path(@app_bookmark), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to app bookmarks", app_bookmarks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this app bookmark", @app_bookmark, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/home_page/index.html.erb
<h1 class="text-3xl font-bold underline">
  Hello world!
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookmarker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>